//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication12.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaasDekont
    {
        public int DekontId { get; set; }
        public short SalonId { get; set; }
        public short PersonelId { get; set; }
        public bool PersonelTuru { get; set; }
        public decimal Miktar { get; set; }
        public System.DateTime Tarih { get; set; }
    
        public virtual Personel Personel { get; set; }
        public virtual Salon Salon { get; set; }
    }
}
