//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication12.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelList
    {
        public long TC { get; set; }
        public short PersonelId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public short SalonId { get; set; }
        public long IBAN { get; set; }
        public string SGKNo { get; set; }
        public string SalonAd { get; set; }
    }
}
